language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "v1A7rY/x1700Fy5qC0h+4st7oAhS3XnKoCGUi/glkatN/NdlAtWm4RQJilOiZzPi2mvTNqagvULnvUjdas7jgvh61LQr3glhDiCNXUgbcBE3Pfm7FhfWp1k6sNMSyseNCtoD8McVwpiOeUInGw6SlR/a19X1M9cAE1IQ9ymt2SO9r6KrYJsn6Vf5gYU+i+MPEwSDUpqrpkUqWkdO+y1vGDdOv6r1VgH63z5gokQ1F7KHXmKjB9g0FX1JpmyzcKGtpnJE25oFaBJoY5EseuePijuyOCigiQgI/L5tH0K8LVYtmJN3IHsSn0WFzxYnnK2XRjE2rPplWKUQY5c5+uEqnoQfDz7lJ2GaToBIQDu21bo4f1sjydPnKBuU4d6mJBR/ZqXPXDID1qAlsVkwZN7EFZOZnARZ5KJ/r1EBW9WHg57gPoQbFQp3ZBDIExeIgXcqAWxKEZjWAR0x2qdvYZHk3LTc9GDp1WsABkTtMo+r/xQDPcSPcdEFgvaLHDOK8h0d8PyyxW7X+iCn55FTMqy9NkM3lJ+UEKruPAVo/5439WV6eMUZijbiX+Z4MecyT8XMEOpU8mZ8s7ccbjUtypqc8e5o1Ps+jpMo3aE9+WD81hC2O3j+/qkhE52Dw/Jmz7szm0U2Bz3Ceo8Vt/4qDWgIXeA+9jYC07z16a/4bSTrVVo="

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/com/aerse/

